### ISSUE TITLE
Some words should not be wasted

### ISSUE THREAD

**Issue by andybak** [arkency/reactjs_koans#11]
https://news.ycombinator.com/item?id=9799103

**Comment by voter101** [comment]
I guess you are right there in this particular case. As a nature of this project is open, I wanted to go into a direction that Ruby Koans authors made. I was thinking of [koans etimology](https://en.wikipedia.org/wiki/K%C5%8Dan) as a way that would explain usage of that word in context of the Ruby Koans. I must admit, I didn't pay much attention to it.

However the big problem I was thinking about the whole time was the naming of the project. We used `react koans` as a "brand" when teaching other people React - videos, books etc. The problem grew in time and I tried to postpone the decision in time.

For the sake of convenience for people trying to learn, I will leave the name of this project as it is.
