### ISSUE TITLE
Failure while running npm run setup

### ISSUE THREAD

**Issue by risonsimon** [arkency/reactjs_koans#19]
This is the error I'm getting.

```
npm ERR! not ok code 0
npm ERR! weird error 3
npm WARN This failure might be due to the use of legacy binary "node"
```

I tried symlink solution and installing nodejs-legacy package from here: http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

But still getting the same issue.

**Comment by voter101** [comment]
Did you try linking `nodejs` with `/usr/bin/node`? It was suggested in this answer and seems to be a good idea.

http://stackoverflow.com/a/21168305/2580798

**Comment by risonsimon** [comment]
It is working now. Thanks.
