### ISSUE TITLE
Slow dependency installing

### ISSUE THREAD

**Issue by glenjamin** [arkency/reactjs_koans#23]
I just tried `npm install`ing this repo over public WiFi, and it took almost 5 minutes!

Obviously you can't do much to make the internet faster, but I noticed you're using the JSX compiler, babel-loader and mocha-traceur - three different ES6 compilers!

I would recommend trimming down to just babel and having everything use the same transform config

**Comment by voter101** [comment]
Thanks for pointing that out. We will take care of that later. Maybe someone else would help us with that before? :)

Thanks for your issue, have a nice day!

**Comment by freak4pc** [comment]
I'm stuck for over an hour at this point. 

`> ws@0.4.31 install /Users/freak4pc/Work/Libs/reactjs_koans/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> ws@0.5.0 install /Users/freak4pc/Work/Libs/reactjs_koans/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/` 

(the bottom slash is animating in rotation)

**Comment by voter101** [comment]
@freak4pc I don't think I am able to help you. It may be caused with slow connection between your computer and NPM servers. Did you try to repeat it? If it does not help, you can open another issue.
