### ISSUE TITLE
missing build/app.js 

### ISSUE THREAD

**Issue by dhoboy** [arkency/reactjs_koans#24]
I tried running the koan files in the browser and get an error that says the /build/app.js file cannot be found.

Where is it? Am I missing something?

**Comment by voter101** [comment]
Hey,

Sorry for missing that. 
Try running `npm run test-es6` first.

**Comment by dhoboy** [comment]
Thanks,

That worked.

Daniel

**Comment by voter101** [comment]
Hey,

Thanks for returning with response. :)

Sorry for a delay. I marked the issue as `in progress` - I will update description. It should be more clear.

**Comment by dhoboy** [comment]
Right on. Thanks Wiktor.

**Comment by nicoleneo** [comment]
app.js doesn't exist. The es6 directory has been removed so I used `npm run test` before `npm run start`.
