### ISSUE TITLE
Test #03, throwing error Invariant Violation: dangerouslyRenderMarkup(...):

### ISSUE THREAD

**Issue by courtneynguyen** [arkency/reactjs_koans#30]
This is the error I am getting:

    03 - What's Your Name? should complete all tasks Task #1 - greet user Should change name in      paragraph on name change in input:
    Error: Invariant Violation: dangerouslyRenderMarkup(...): 
    Cannot render markup in a worker     thread. Make sure `window` and `document` are available globally before requiring React when unit     testing or use React.renderToString for server rendering.
          at Context.<anonymous> (test/es6/03-WhatsYourName.js:35:41)

And this is my test code: 

    var test = (<div>
    <p>Hey there. Enter your name.</p>
     <input type="text" name="name" onChange={this.onNameChange} />
        </div>);
        if(this.state.name.length === 0)
          return test;
        else{
          return (
            <div>
              <p>Hello {this.state.name}</p>
              <input type="text" name="name" onChange={this.onNameChange} />
            </div>
          );
        }

I couldn't figure out how to solve the error. From what I could tell, my program worked. I did a some Googling, and it might be because of the way  you are requiring the packages, but I am not sure.

**Comment by voter101** [comment]
Thanks for reporting that. That was my mistake and it is fixed now.

Have a nice day! :)
