### ISSUE TITLE
webpack requires node-libs-browser peer

### ISSUE THREAD

**Issue by alexlrobertson** [arkency/reactjs_koans#32]
`npm WARN EPEERINVALID webpack@1.10.1 requires a peer of node-libs-browser@>= 0.4.0 <=0.6.0 but none was installed.`

**Comment by voter101** [comment]
Did you get this message during installation?

What's you npm version? You can check that by entering `npm -v` into terminal.

**Comment by alexlrobertson** [comment]
I had to install `babel-loader` because of a peer dependency as well.

I'm using npm 3.1.0 which is known to require peer dependencies to be installed.

**Comment by voter101** [comment]
Ok, no more warnings - I got it fixed.

Thanks for reporting the issue. Have a nice day!

**Comment by alexlrobertson** [comment]
Thanks!
