### ISSUE TITLE
OSX: Can't launch server & tests return nothing

### ISSUE THREAD

**Issue by inem** [arkency/reactjs_koans#36]
<img width="469" alt="reactjs_koans_ _bash_ _204x46" src="https://cloud.githubusercontent.com/assets/9665/8742098/fbb052c8-2c61-11e5-98db-a6a3430cc356.png">
Everything I did - is that I changed text "\<div\>FILL ME IN!\</div\>" to "Hello world" in first example.

Oh, and now I upgraded node from 0.10.32 to 0.12.2_1 and I now get this even with untouched examples:
https://gist.github.com/inem/a037c7616d8044527ab3

Why it happens all the time I try do something with node??!!

**Comment by voter101** [comment]
Did you try `npm rebuild`?

**Comment by inem** [comment]
Oh, thanks! That helped. Probably you should add required `node` version to README

**Comment by voter101** [comment]
I guess the problem wasn't with node version. Wasn't it?
