### ISSUE TITLE
TypeError while running `npm run test-es6`

### ISSUE THREAD

**Issue by rioc0719** [arkency/reactjs_koans#43]
I'm getting the following error while running `npm run test-es6`:

    TypeError: Cannot read property 'scryRenderedDOMComponentsWithTag' of undefined                                                                                  
      at Context.<anonymous> (test/es6/01-HelloWorld.js:18:41)

I did some console logging and I found that there is no `TestUtils` property on the `React.addons` object used in the file, which means that the testing script fails in `it("should complete all tasks", ...)`. I already tried `npm rebuild` and downloading the entire project again from Github, but the problem persists.

Is this a bug or am I doing something stupid?

**Comment by voter101** [comment]
What's your version of Node and NPM? 
`node --version` and `npm -v`

**Comment by rioc0719** [comment]
@voter101 My Node version is 0.12.7 and I thought I was using npm 2.14.2 but nvm was messing with my PATH and I was actually using npm 2.11.3. Fixing my PATH fixed the problem. Sorry for bothering.
