### ISSUE TITLE
Simpler solution for Grocery Challenge Part 4?

### ISSUE THREAD

**Issue by bronson** [arkency/reactjs_koans#44]
You say:

```js
  // Fill the definition of the following method to allow completing each item
  // Hint 1: Pay attention to the element's index on the list.
```

This is what I came up with:

```js
  toggleGroceryCompleteness(groceryIndex) {
    var newState = React.addons.update(this.state, {
      groceries: {[groceryIndex]: {completed: {$set: true}}}
    });
    this.setState(newState)
  }
```

But this seems odd because you never told us about React.addons.update.

Is there a simpler solution that I'm overlooking?  Thanks!

**Comment by voter101** [comment]
Hello @bronson,

Using `React.addons.update` is OK. If you want, go for it. However you could just get the mutation done like this:

```javascript
toggleGroceryCompleteness(groceryIndex) {
  var state = Object.assign({}, this.state}); // It's new ES2015 / ES6 stuff
  state.groceries[groceryIndex].completed = true;
  this.setState(state);
}
```

**Comment by bronson** [comment]
Pretty sure this solution violates the "*NEVER mutate this.state directly*" warning, doesn't it?

https://facebook.github.io/react/docs/component-api.html

(sure, it's probably safe here where updates will never happen very fast, but that seems a bad habit to get into...)

**Comment by voter101** [comment]
It won't crash if you mutate it to set later, React will check on that and do some stuff around. This note in documentation warns before changing `state` and not setting it later (with `setState` method). It may overwrite your changes with next `setState`.

**Comment by bronson** [comment]
Still sounds like it violates it though.  :)  Though, I agree, it will work just fine here.

Closing since you've given me the info I need.  Thank you!

**Comment by antibland** [comment]
@voter101 @bronson I had a similar issue with the violation. Here's what I came up with to avoid using the plugin and the direct data mutation:

```javascript
toggleGroceryCompleteness(groceryIndex) {
  let groceries = [];
  let currentState;

  // rebuild the groceries array
  for(let index = 0; index < this.state.groceries.length; index++) {
    groceries.push({ name: this.state.groceries[index].name });
    currentState = this.state.groceries[index].completed;

    // if the index matches the groceryIndex, swap the state
    groceries[index].completed = index === groceryIndex ? !currentState : currentState
  }

  this.setState({groceries: groceries});
}
```
