### ISSUE TITLE
Setup doesnt work with latest node

### ISSUE THREAD

**Issue by darrenturn90** [arkency/reactjs_koans#48]
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs_koans@0.0.3 setup script 'npm install && ncp koans/ exercises/'.
npm ERR! This is most likely a problem with the reactjs_koans package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && ncp koans/ exercises/

**Comment by voter101** [comment]
Related with: https://github.com/arkency/reactjs_koans/issues/45

**Comment by voter101** [comment]
It's already fixed.
