### ISSUE TITLE
Running test ends with no feedback output

### ISSUE THREAD

**Issue by chrisdziewa** [arkency/reactjs_koans#54]
When I run `npm run test`, nothing is output before the command finishes besides the command being issued. As a side note-in the browser, I am able to see my changes correctly.

**Comment by voter101** [comment]
What OS are you using? What is your node version?

**Comment by chrisdziewa** [comment]
I am on Mac Yosemite. My node version is 4.2.3

**Comment by voter101** [comment]
Hey,

Sorry for a late response.

I've tried in on my OS X El Capitan on Node 4.2.3 with NPM 2.14.7 and it's working. Are you sure you issued `npm run setup`?

<img width="936" alt="screen shot 2016-01-02 at 18 27 24" src="https://cloud.githubusercontent.com/assets/2883685/12075375/805dce3c-b17e-11e5-8977-344cebfc13d4.png">

**Comment by chrisdziewa** [comment]
That may have been it. I no longer have it on my computer. Maybe I'll try
it again another time. Feel free to close the issue. Thanks for looking
into it for me.
Le 2 janv. 2016 11:28 AM, "Wiktor Mociun" <notifications@github.com> a
écrit :

**Comment by voter101** [comment]
Hey,

I checked this - if you don't run `npm run setup`, the `npm test` will return empty input. ;)

**Comment by voter101** [comment]
And you've most probably didn't run the `npm install` command. :)
