### ISSUE TITLE
Tests don't output anything

### ISSUE THREAD

**Issue by C-F-K** [arkency/reactjs_koans#57]
I'm sure that very interesting things are happening when I run `npm run test`, but none of it is showing up in the terminal. All that I get (after the output from `npm run compile`) is the message "ECHO is on", but the first test should be failing and causing mocha to bail.

It may be worth noting that executing the commands separately, as listed in `package.json` (redirecting the output of `mocha` to a file because `||` isn't a valid separator in Win7 PowerShell), generates the same output for `npm run compile` and nothing at all for `mocha`.

**Comment by voter101** [comment]
Can you propose how these scripts should look like? I will make the script that will the right commands based on OS. I tested it out on my Win10 with `cmd.exe` and standard Node installation. I must admit I am not really aware how it should really work on PowerShell.

**Comment by C-F-K** [comment]
I just tried it with a `cmd.exe` shell inside my PowerShell session, as well as in a separate `cmd` shell, and the same thing happened as when running directly from PowerShell. I think npm automatically adapts the value of the properties in the `"scripts"` section of `package.json` for the OS; otherwise, running `npm run test` would give the same error as trying to use `||` as a separator directly, which it doesn't.

Can you provide a screenshot or copy-paste of what I should see in the screenshot when the first test fails?

**Comment by voter101** [comment]
![screen shot 2016-01-17 at 23 58 14](https://cloud.githubusercontent.com/assets/2883685/12380572/37f7ed54-bd76-11e5-999b-a7031aa6b6ff.png)

**Comment by C-F-K** [comment]
Thanks. It looks there there *used* to be a bug in Mocha where piped output wouldn't be written, but it says it was closed in June 2015. I'm not sure why the same thing appears to be happening now; I'm running mocha v2.3.4, node v4.2.4, npm v2.14.12. Will try testing something else for comparison purposes.

**Comment by C-F-K** [comment]
I've tried basically everything I can think of at this point, to no avail. I'll just run this on my Win10 laptop, I guess. Let me know if there's anything I can add to help reproduce the problem.

**Comment by voter101** [comment]
I am locking this issue. If you have any idea how to point me to the right direction, please open it up again. :)
