### ISSUE TITLE
Tests throw error, module not found.

### ISSUE THREAD

**Issue by Ulthes** [arkency/reactjs_koans#62]
Path to source files is wrong. For instance we have

```jsx
import HelloWorld from '../src/01-HelloWorld.js';
```
and it should be

```jsx
import HelloWorld from '../koans/01-HelloWorld.jsx';
```

I'll submit pull request in a second.

**Comment by voter101** [comment]
Did you run `npm run setup` first? :)

**Comment by Ulthes** [comment]
...Ok, I'm an idiot, sorry :). Didn't read the whole README, went for the project like hot rocket.
