### ISSUE TITLE
Extra Task in the Grocery List

### ISSUE THREAD

**Issue by danyim** [arkency/reactjs_koans#64]
I wasn't sure what the prompt meant by "extracting creation of grocery to an external service". Could someone clarify or provide a hint?

**In 05-Challenge-GroceryList-part-4.jsx:**
```javascript
// Extra Task: Extract creation (`addGroceryItem`) of grocery to external service.
```

Thank you for creating these koans, by the way.

**Comment by voter101** [comment]
@danyim, after peeking into that, I don't understand what we meant by this additional task way back when we designed this exercise. I removed it, sorry for wasting your effort.

Thanks for your help!
