### ISSUE TITLE
Using the console to look at props and event.target

### ISSUE THREAD

**Issue by Sheng-Long** [arkency/reactjs_koans#65]
In the exercises, you mention using console to look at different special variables such as this.props and event.target, however when I try to do it, it comes up with "undefined" or something similar.  Is there any way you could give a more in depth explanation of this process?

What I tried to do was going to the inspect screen in both chrome and firefox, clicking over to the 'Console' tab, then either typing in console.log(event.target) or just typing in event.target.  Again, neither of these come up with any information, just 'undefined' or something similarly nondescript.

P.S.
Thank you very much for making this, it took me a week to find a tutorial that works for me.  And this one really works for me!

**Comment by voter101** [comment]
>What I tried to do was going to the inspect screen in both chrome and firefox, clicking over to the 'Console' tab, then either typing in console.log(event.target) or just typing in event.target. Again, neither of these come up with any information, just 'undefined' or something similarly nondescript.

This is desired, as when you do it this way, you are logging variables from a top-level browser environment (it tries to find `window.event.target`, which does not exist).

Try doing `console.log` from the function (put `console.log(event)` INSIDE this function) that has `event` as an argument.

**Comment by Sheng-Long** [comment]
Thank you voter, this helped
