### ISSUE TITLE
The setup doesn't appear to be working from a windows environment

### ISSUE THREAD

**Issue by voter101** [arkency/reactjs_koans#9]
Comment from Hacker News: https://news.ycombinator.com/item?id=9799539

Full description: 
>The setup doesn't appear to be working from a windows/mingw32 environment. (Most npm installers do work in this environment.)

**Comment by Azolo** [comment]
The setup command calls `scripts/setup.sh` which is a Bash script and won't run properly on Windows.

**Comment by Azolo** [comment]
Likewise the `start` command in `npm-scripts` depends on a Hashbang to run which Windows also doesn't support.

**Comment by voter101** [comment]
@eTorAken had some problems with installation on Windows. I'll make sure it works on minimum setup on Windows and update Readme if needed.

>$ npm run test-es6
>
> reactjs_koans@0.0.1 test-es6 c:\wamp\www\reactjs_koans
> jsx -x jsx --es6module exercises/es6 src/es6 >/dev/null && mocha -b --compilers js:mocha-traceur -r test/es6/helpers.js test/es6/**/*.js & true
>
>The specified path was not found.

**Comment by janpieterz** [comment]
I changed my scripts to:


```
  "scripts": {
    "compile": "babel exercises/es6 --out-dir src/es6 > NUL",
    "setup": "npm install && ncp koans/ exercises/",
    "start": "npm run compile > NUL && nodemon server.js",
    "test-es6": "npm run compile > NUL && mocha -b --compilers js:babel/register -r test/es6/helpers.js test/es6/**/*.js || true",
    "watch": "onchange exercises/es6/*.jsx -- npm run test-es6"
  },
```
Which makes it work but not the test-es6 part (it runs but basically crashes afterwards). So the error of unspecified path can be solved by just removing the piping to NUL or /dev/null and get some more outpu, or perhaps making a specific set of commands for windows.

Error log I still have below:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-es6"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! reactjs_koans@0.0.3 test-es6: `npm run compile > NUL && mocha -b --comp
ilers js:babel/register -r test/es6/helpers.js test/es6/**/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactjs_koans@0.0.3 test-es6 script 'npm run compile > NU
L && mocha -b --compilers js:babel/register -r test/es6/helpers.js test/es6/**/*
.js'.

**Comment by chaseha** [comment]
having same issues. npm run setup crashes with bunches of errors. any progress?

**Comment by voter101** [comment]
Hey. Unfortunatelly I am not having any running Windows machine and free time to look onto that issue...  

Help would be really appreciated here.

**Comment by WMeldon** [comment]
I'll probably give this a look if I have time.  The issue with using NPM run as opposed to a task runner like Grunt is portability (and by that I mean it doesn't work on Windows :disappointed:).  Unfortunately, that means more potential overhead.

**Comment by voter101** [comment]
Guys, I hope this PR fixes your problems: https://github.com/arkency/reactjs_koans/pull/56

I managed to successfully run the whole project with those changes.
